version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  web:
    build: .
    command: python3 app.py
    environment:
      - DEBUG=True # set an env var for flask
    depends_on:
      - es
    ports:
      - 5050:5050
    volumes:
      - ./flask-app:/opt/flask-app
volumes:
    esdata1:
      driver: local
